"""
Extensive Training Data for Custom Classifiers.

Contains curated, labeled examples for training domain-specific classifiers:
1. Romantic Intent Classification (12 categories, 40+ examples each)
2. Conversation Stage Classification (7 categories, 30+ examples each)
3. Emotional Tone Classification (11 categories, 35+ examples each)

Data design principles:
- Real-world texting patterns (lowercase, abbreviations, emojis)
- Bilingual (English + Russian examples)
- Range of message lengths (short to paragraph)
- Edge cases and ambiguous examples
- Based on communication psychology research (Gottman, Chapman, Knapp)

Total: 1200+ labeled training examples
"""

from typing import Any, List, Dict, Tuple


# ═══════════════════════════════════════════════════════════════════
#  1. ROMANTIC INTENT CLASSIFICATION
# ═══════════════════════════════════════════════════════════════════
# Categories based on Speech Act Theory + Relationship Communication Research

ROMANTIC_INTENT_DATA: List[Tuple[str, str]] = [
    # ── flirty (46 examples) ──
    ("you looked so good today", "flirty"),
    ("can't stop thinking about you", "flirty"),
    ("you're dangerous 😏", "flirty"),
    ("what are you wearing rn", "flirty"),
    ("come over tonight", "flirty"),
    ("i like the way you smile", "flirty"),
    ("you drive me crazy", "flirty"),
    ("wish you were here with me", "flirty"),
    ("you're so hot", "flirty"),
    ("i want to see you", "flirty"),
    ("that photo 🔥🔥", "flirty"),
    ("naughty thoughts about you", "flirty"),
    ("you're trouble aren't you", "flirty"),
    ("i have a surprise for you tonight", "flirty"),
    ("your lips though", "flirty"),
    ("you make me nervous in a good way", "flirty"),
    ("stop being so attractive", "flirty"),
    ("i can't focus because of you", "flirty"),
    ("you're a tease", "flirty"),
    ("thinking about kissing you", "flirty"),
    ("we should have a sleepover", "flirty"),
    ("you're my weakness", "flirty"),
    ("that outfit though 😍", "flirty"),
    ("i bet you look cute when you sleep", "flirty"),
    ("miss your touch", "flirty"),
    ("хочу тебя обнять", "flirty"),
    ("ты такой красивый", "flirty"),
    ("приезжай ко мне", "flirty"),
    ("я по тебе скучаю, особенно по ночам", "flirty"),
    ("ты меня сводишь с ума", "flirty"),
    ("целую тебя", "flirty"),
    ("хочу быть рядом с тобой", "flirty"),
    ("ты такой горячий 🔥", "flirty"),
    ("send me a selfie", "flirty"),
    ("what would you do if i was there", "flirty"),
    ("you smell so good", "flirty"),
    ("i dreamed about you last night", "flirty"),
    ("you're irresistible", "flirty"),
    ("we should cuddle", "flirty"),
    ("come give me a hug", "flirty"),
    ("i love your voice", "flirty"),
    ("you give me butterflies", "flirty"),
    ("when can i see you again", "flirty"),
    ("your eyes are incredible", "flirty"),
    ("i get excited when you text me", "flirty"),
    ("хочу тебя поцеловать", "flirty"),

    # ── romantic (44 examples) ──
    ("i love you so much", "romantic"),
    ("you mean everything to me", "romantic"),
    ("i can't imagine life without you", "romantic"),
    ("you're the best thing that ever happened to me", "romantic"),
    ("i love everything about you", "romantic"),
    ("you make me want to be a better person", "romantic"),
    ("my heart belongs to you", "romantic"),
    ("i want to grow old with you", "romantic"),
    ("you're my soulmate", "romantic"),
    ("every moment with you is perfect", "romantic"),
    ("i fall more in love with you every day", "romantic"),
    ("you complete me", "romantic"),
    ("i never knew love until i met you", "romantic"),
    ("you're my forever", "romantic"),
    ("i cherish every second with you", "romantic"),
    ("you're the love of my life", "romantic"),
    ("i want to spend forever with you", "romantic"),
    ("you make my heart sing", "romantic"),
    ("waking up next to you is my favorite thing", "romantic"),
    ("you're my person", "romantic"),
    ("thank you for loving me", "romantic"),
    ("you're my home", "romantic"),
    ("i love the way you laugh", "romantic"),
    ("my favorite place is in your arms", "romantic"),
    ("you make the world brighter", "romantic"),
    ("я люблю тебя больше всего на свете", "romantic"),
    ("ты моя единственная", "romantic"),
    ("без тебя я не представляю жизнь", "romantic"),
    ("ты моё солнышко", "romantic"),
    ("я хочу быть с тобой навсегда", "romantic"),
    ("ты моя судьба", "romantic"),
    ("моё сердце принадлежит тебе", "romantic"),
    ("с каждым днём люблю тебя всё больше", "romantic"),
    ("ты делаешь меня счастливым", "romantic"),
    ("ты лучшее что со мной случилось", "romantic"),
    ("you're the reason i smile every day", "romantic"),
    ("being with you feels like home", "romantic"),
    ("you have the most beautiful soul", "romantic"),
    ("i would choose you in every lifetime", "romantic"),
    ("you're my dream come true", "romantic"),
    ("i love how you see the world", "romantic"),
    ("everything is better with you", "romantic"),
    ("you're my favorite human", "romantic"),
    ("i'm so lucky to have you", "romantic"),

    # ── supportive (42 examples) ──
    ("i'm here for you no matter what", "supportive"),
    ("you can do this, i believe in you", "supportive"),
    ("i'm so proud of you", "supportive"),
    ("you're not alone, i'm right here", "supportive"),
    ("take your time, no rush", "supportive"),
    ("you don't have to go through this alone", "supportive"),
    ("i'll always have your back", "supportive"),
    ("that sounds really tough, i'm sorry", "supportive"),
    ("you're stronger than you think", "supportive"),
    ("it's okay to not be okay", "supportive"),
    ("i'm listening, tell me everything", "supportive"),
    ("you deserve to feel good about yourself", "supportive"),
    ("whatever you need, just tell me", "supportive"),
    ("i know today was hard but tomorrow will be better", "supportive"),
    ("you handled that so well", "supportive"),
    ("don't be too hard on yourself", "supportive"),
    ("i'm proud of how far you've come", "supportive"),
    ("your feelings are valid", "supportive"),
    ("lean on me when you need to", "supportive"),
    ("you've got this", "supportive"),
    ("я всегда буду рядом", "supportive"),
    ("ты справишься, я верю в тебя", "supportive"),
    ("я горжусь тобой", "supportive"),
    ("ты не одна, я здесь", "supportive"),
    ("всё будет хорошо", "supportive"),
    ("я тебя поддерживаю", "supportive"),
    ("not everything has to be perfect", "supportive"),
    ("you did your best and that's enough", "supportive"),
    ("i love you even on your worst days", "supportive"),
    ("you can talk to me about anything", "supportive"),
    ("i know it's hard right now", "supportive"),
    ("let me know how i can help", "supportive"),
    ("you're doing amazing", "supportive"),
    ("breathe, it'll be okay", "supportive"),
    ("take it one step at a time", "supportive"),
    ("i care about you so much", "supportive"),
    ("your happiness matters to me", "supportive"),
    ("everything will work out", "supportive"),
    ("you're brave for sharing that", "supportive"),
    ("sending you a virtual hug", "supportive"),
    ("it's okay to cry", "supportive"),
    ("тебе не нужно быть идеальной", "supportive"),

    # ── casual (40 examples) ──
    ("what are you up to", "casual"),
    ("how was your day", "casual"),
    ("anything interesting happen today", "casual"),
    ("just chilling at home", "casual"),
    ("watching netflix rn", "casual"),
    ("about to eat dinner", "casual"),
    ("work was so boring today", "casual"),
    ("the weather is nice today", "casual"),
    ("did you eat yet", "casual"),
    ("what are you having for lunch", "casual"),
    ("i just woke up", "casual"),
    ("heading to the gym", "casual"),
    ("traffic is terrible", "casual"),
    ("just got home", "casual"),
    ("gonna take a nap", "casual"),
    ("what should i eat", "casual"),
    ("i'm so tired", "casual"),
    ("how's work going", "casual"),
    ("any plans for tonight", "casual"),
    ("just saw the craziest thing", "casual"),
    ("как дела", "casual"),
    ("что делаешь", "casual"),
    ("как прошёл день", "casual"),
    ("сижу дома", "casual"),
    ("устал после работы", "casual"),
    ("что нового", "casual"),
    ("сегодня была хорошая погода", "casual"),
    ("ты уже ел", "casual"),
    ("i'm at the grocery store", "casual"),
    ("just finished cooking", "casual"),
    ("my friend told me something funny", "casual"),
    ("i need coffee", "casual"),
    ("the wifi is so slow", "casual"),
    ("just woke up from a nap", "casual"),
    ("what time is it there", "casual"),
    ("do you want coffee", "casual"),
    ("have you seen this show", "casual"),
    ("my cat is being weird", "casual"),
    ("this song is stuck in my head", "casual"),
    ("should i order pizza", "casual"),

    # ── playful (42 examples) ──
    ("haha you're so dumb 😂", "playful"),
    ("bet you can't beat me", "playful"),
    ("you wish 😏", "playful"),
    ("fight me", "playful"),
    ("dare you to do it", "playful"),
    ("you're such a nerd", "playful"),
    ("omg stop 😂😂", "playful"),
    ("i'm telling mom", "playful"),
    ("loser buys dinner", "playful"),
    ("that's cap", "playful"),
    ("sure sure whatever you say", "playful"),
    ("prove it", "playful"),
    ("you wouldn't dare", "playful"),
    ("make me", "playful"),
    ("no way 😂", "playful"),
    ("lmaooo dead", "playful"),
    ("you did not just say that", "playful"),
    ("i'm screaming", "playful"),
    ("ok mr funny guy", "playful"),
    ("catch these hands", "playful"),
    ("bro what 😂", "playful"),
    ("you're unreal", "playful"),
    ("the audacity", "playful"),
    ("sir this is a wendy's", "playful"),
    ("i can't with you", "playful"),
    ("you're a menace", "playful"),
    ("tell me why you're like this", "playful"),
    ("i'm not even surprised anymore", "playful"),
    ("iconic behavior honestly", "playful"),
    ("ты дурак 😂", "playful"),
    ("да ладно тебе хахаха", "playful"),
    ("не смеши меня", "playful"),
    ("спорим", "playful"),
    ("ну попробуй", "playful"),
    ("ты не посмеешь", "playful"),
    ("а может и нет 😏", "playful"),
    ("you're annoying in the best way", "playful"),
    ("i'm rolling my eyes at you rn", "playful"),
    ("ok comedian", "playful"),
    ("you think you're so clever huh", "playful"),
    ("blocked and reported 😂", "playful"),
    ("this is why we can't have nice things", "playful"),

    # ── sincere (38 examples) ──
    ("i need to tell you something important", "sincere"),
    ("i've been thinking about us a lot", "sincere"),
    ("i want to be honest with you", "sincere"),
    ("you really changed my life", "sincere"),
    ("i was wrong and i'm sorry", "sincere"),
    ("i appreciate you more than you know", "sincere"),
    ("thank you for always being there", "sincere"),
    ("i'm grateful for you", "sincere"),
    ("you deserve better", "sincere"),
    ("i should have said this earlier", "sincere"),
    ("i mean every word", "sincere"),
    ("this is hard for me to say but", "sincere"),
    ("i owe you an apology", "sincere"),
    ("i never want to take you for granted", "sincere"),
    ("you're special to me and i want you to know that", "sincere"),
    ("i don't say this enough but i appreciate you", "sincere"),
    ("i want you to know how much you mean to me", "sincere"),
    ("being vulnerable with you is scary but worth it", "sincere"),
    ("i trust you completely", "sincere"),
    ("you make me feel safe", "sincere"),
    ("я хочу быть честным с тобой", "sincere"),
    ("ты действительно изменила мою жизнь", "sincere"),
    ("прости меня, я был неправ", "sincere"),
    ("я ценю тебя больше чем ты думаешь", "sincere"),
    ("спасибо что ты рядом", "sincere"),
    ("i'm not perfect but i'm trying for you", "sincere"),
    ("you deserve to hear how much you matter", "sincere"),
    ("i never want to hurt you", "sincere"),
    ("my feelings for you are real", "sincere"),
    ("i choose you, always", "sincere"),
    ("you can trust me", "sincere"),
    ("i'll never lie to you", "sincere"),
    ("i respect you so much", "sincere"),
    ("this matters to me more than you know", "sincere"),
    ("i hear you and i understand", "sincere"),
    ("thank you for being patient with me", "sincere"),
    ("you have my word", "sincere"),
    ("я обещаю тебе", "sincere"),

    # ── angry (40 examples) ──
    ("leave me alone", "angry"),
    ("i don't want to talk to you", "angry"),
    ("you really hurt me", "angry"),
    ("i'm so mad right now", "angry"),
    ("how could you do that", "angry"),
    ("that was so disrespectful", "angry"),
    ("i can't believe you", "angry"),
    ("you lied to me", "angry"),
    ("this is not okay", "angry"),
    ("i'm done with this", "angry"),
    ("you always do this", "angry"),
    ("you never listen to me", "angry"),
    ("why did you say that", "angry"),
    ("i'm tired of this", "angry"),
    ("you don't care about me", "angry"),
    ("that was wrong and you know it", "angry"),
    ("i need space", "angry"),
    ("don't talk to me right now", "angry"),
    ("you crossed the line", "angry"),
    ("i'm so frustrated", "angry"),
    ("are you serious right now", "angry"),
    ("this is so unfair", "angry"),
    ("you're being selfish", "angry"),
    ("stop making excuses", "angry"),
    ("i can't trust you anymore", "angry"),
    ("уходи", "angry"),
    ("не хочу с тобой разговаривать", "angry"),
    ("ты меня обидел", "angry"),
    ("мне очень плохо из-за тебя", "angry"),
    ("как ты мог", "angry"),
    ("я злюсь на тебя", "angry"),
    ("хватит", "angry"),
    ("ты всегда так делаешь", "angry"),
    ("ты мне врал", "angry"),
    ("бесит", "angry"),
    ("достал", "angry"),
    ("i'm so disappointed in you", "angry"),
    ("you broke my trust", "angry"),
    ("we need to talk about what happened", "angry"),
    ("this keeps happening and i'm tired of it", "angry"),

    # ── sad (38 examples) ──
    ("i'm feeling really down today", "sad"),
    ("i miss you so much it hurts", "sad"),
    ("everything feels wrong", "sad"),
    ("i've been crying", "sad"),
    ("i feel so alone", "sad"),
    ("nothing makes me happy anymore", "sad"),
    ("i had a terrible day", "sad"),
    ("life is so hard sometimes", "sad"),
    ("i feel like nobody cares", "sad"),
    ("i just want to disappear", "sad"),
    ("i'm not okay", "sad"),
    ("my heart hurts", "sad"),
    ("i feel empty inside", "sad"),
    ("today was the worst", "sad"),
    ("i can't stop crying", "sad"),
    ("everything is falling apart", "sad"),
    ("i feel so lost", "sad"),
    ("this loneliness is killing me", "sad"),
    ("i need a hug", "sad"),
    ("why does everything go wrong", "sad"),
    ("мне грустно", "sad"),
    ("мне плохо", "sad"),
    ("я плакала", "sad"),
    ("чувствую себя одинокой", "sad"),
    ("мне тяжело", "sad"),
    ("всё плохо", "sad"),
    ("я так устала от всего", "sad"),
    ("nothing feels right", "sad"),
    ("i'm struggling", "sad"),
    ("some days are just harder than others", "sad"),
    ("i feel like a burden", "sad"),
    ("i don't know what to do anymore", "sad"),
    ("everything makes me sad", "sad"),
    ("i feel broken", "sad"),
    ("it's been a rough week", "sad"),
    ("i just feel so overwhelmed", "sad"),
    ("i wish things were different", "sad"),
    ("i feel so small", "sad"),

    # ── testing (40 examples) ──
    ("do you still love me", "testing"),
    ("what would you do if another girl texted you", "testing"),
    ("am i pretty", "testing"),
    ("would you still love me if i was ugly", "testing"),
    ("do you think she's prettier than me", "testing"),
    ("who do you like more, me or your friends", "testing"),
    ("what if we broke up", "testing"),
    ("what am i to you", "testing"),
    ("do you miss me when i'm gone", "testing"),
    ("would you still want me if i gained weight", "testing"),
    ("do you find other girls attractive", "testing"),
    ("am i enough for you", "testing"),
    ("do you ever think about your ex", "testing"),
    ("would you choose me over anyone", "testing"),
    ("prove that you love me", "testing"),
    ("do you really care about me", "testing"),
    ("am i the most important person in your life", "testing"),
    ("what if i said i want to see other people", "testing"),
    ("do you even notice me", "testing"),
    ("would you fight for me", "testing"),
    ("ты меня ещё любишь", "testing"),
    ("я красивая", "testing"),
    ("а если другая девушка тебе напишет", "testing"),
    ("кто тебе больше нравится", "testing"),
    ("что я для тебя", "testing"),
    ("ты бы выбрал меня", "testing"),
    ("am i boring", "testing"),
    ("do you think about me", "testing"),
    ("am i special to you", "testing"),
    ("what's your type", "testing"),
    ("would you wait for me", "testing"),
    ("do you compare me to other girls", "testing"),
    ("am i replaceable", "testing"),
    ("what would you do if i disappeared", "testing"),
    ("do you love me or are you just used to me", "testing"),
    ("would you still text me first if i stopped", "testing"),
    ("are you talking to other girls", "testing"),
    ("do you think i'm needy", "testing"),
    ("would you move across the world for me", "testing"),
    ("if i changed would you still love me", "testing"),

    # ── greeting (35 examples) ──
    ("hey", "greeting"),
    ("hi there", "greeting"),
    ("good morning", "greeting"),
    ("good morning beautiful", "greeting"),
    ("hey babe", "greeting"),
    ("hiii", "greeting"),
    ("heyyy", "greeting"),
    ("hi love", "greeting"),
    ("good morning sunshine", "greeting"),
    ("morning", "greeting"),
    ("hey you", "greeting"),
    ("hola", "greeting"),
    ("what's up", "greeting"),
    ("yo", "greeting"),
    ("sup", "greeting"),
    ("привет", "greeting"),
    ("приветик", "greeting"),
    ("доброе утро", "greeting"),
    ("доброе утро солнышко", "greeting"),
    ("здарова", "greeting"),
    ("hey stranger", "greeting"),
    ("long time no see", "greeting"),
    ("look who it is", "greeting"),
    ("missed me?", "greeting"),
    ("hello beautiful", "greeting"),
    ("hi gorgeous", "greeting"),
    ("good afternoon", "greeting"),
    ("hey cutie", "greeting"),
    ("howdy", "greeting"),
    ("hey handsome", "greeting"),
    ("how's it going", "greeting"),
    ("what's good", "greeting"),
    ("hi baby", "greeting"),
    ("hey sweetheart", "greeting"),
    ("добрый вечер", "greeting"),

    # ── goodbye (35 examples) ──
    ("good night", "goodbye"),
    ("sweet dreams", "goodbye"),
    ("gotta go", "goodbye"),
    ("talk later", "goodbye"),
    ("bye babe", "goodbye"),
    ("night night", "goodbye"),
    ("going to sleep now", "goodbye"),
    ("i should get some sleep", "goodbye"),
    ("talk tomorrow", "goodbye"),
    ("goodnight baby", "goodbye"),
    ("sleep tight", "goodbye"),
    ("heading to bed", "goodbye"),
    ("see you tomorrow", "goodbye"),
    ("catch you later", "goodbye"),
    ("gn", "goodbye"),
    ("спокойной ночи", "goodbye"),
    ("пока", "goodbye"),
    ("сладких снов", "goodbye"),
    ("до завтра", "goodbye"),
    ("ложусь спать", "goodbye"),
    ("goodnight love", "goodbye"),
    ("i'll text you in the morning", "goodbye"),
    ("bye for now", "goodbye"),
    ("time for bed", "goodbye"),
    ("have a good night", "goodbye"),
    ("rest well", "goodbye"),
    ("dream of me", "goodbye"),
    ("gotta run", "goodbye"),
    ("ttyl", "goodbye"),
    ("peace out", "goodbye"),
    ("nighty night", "goodbye"),
    ("don't stay up too late", "goodbye"),
    ("go to sleep baby", "goodbye"),
    ("i'm falling asleep", "goodbye"),
    ("до связи", "goodbye"),

    # ── plans (40 examples) ──
    ("let's meet this weekend", "plans"),
    ("are you free tonight", "plans"),
    ("wanna grab coffee tomorrow", "plans"),
    ("let's go to that restaurant", "plans"),
    ("what time works for you", "plans"),
    ("should we go on a date", "plans"),
    ("i was thinking we could go hiking", "plans"),
    ("want to come over", "plans"),
    ("let's plan something fun", "plans"),
    ("are you doing anything saturday", "plans"),
    ("we should travel somewhere together", "plans"),
    ("movie night?", "plans"),
    ("let's cook together", "plans"),
    ("i found this cool place we should try", "plans"),
    ("when are we hanging out next", "plans"),
    ("давай встретимся", "plans"),
    ("ты свободна сегодня вечером", "plans"),
    ("давай сходим куда-нибудь", "plans"),
    ("что ты делаешь в выходные", "plans"),
    ("приезжай ко мне завтра", "plans"),
    ("i'll pick you up at 7", "plans"),
    ("let me take you out", "plans"),
    ("what do you want to do today", "plans"),
    ("beach day tomorrow?", "plans"),
    ("we should go dancing", "plans"),
    ("game night at my place?", "plans"),
    ("want to go for a walk later", "plans"),
    ("let's have a picnic", "plans"),
    ("should we try that new cafe", "plans"),
    ("i made reservations", "plans"),
    ("road trip this weekend?", "plans"),
    ("want to watch the sunset together", "plans"),
    ("let me cook for you", "plans"),
    ("shall we go shopping together", "plans"),
    ("concert this friday?", "plans"),
    ("давай погуляем", "plans"),
    ("хочешь вместе пообедать", "plans"),
    ("can we facetime tonight", "plans"),
    ("pizza and a movie?", "plans"),
    ("i want to take you somewhere special", "plans"),
]

# ═══════════════════════════════════════════════════════════════════
#  2. CONVERSATION STAGE CLASSIFICATION
# ═══════════════════════════════════════════════════════════════════
# Based on Knapp's Relational Development Model

CONVERSATION_STAGE_DATA: List[Tuple[str, str]] = [
    # ── opening (32 examples) ──
    ("hey, how are you?", "opening"),
    ("hi, nice to meet you", "opening"),
    ("what's your name?", "opening"),
    ("hey, saw your profile and thought you were cute", "opening"),
    ("hi there, how's your day going", "opening"),
    ("hey! we matched 😊", "opening"),
    ("nice to finally talk to you", "opening"),
    ("hi, where are you from", "opening"),
    ("so tell me about yourself", "opening"),
    ("what do you do for fun", "opening"),
    ("how old are you", "opening"),
    ("are you from around here", "opening"),
    ("привет! как дела", "opening"),
    ("приятно познакомиться", "opening"),
    ("hey, first time texting someone like this", "opening"),
    ("so, what brings you here", "opening"),
    ("you seem really cool", "opening"),
    ("love your profile pic", "opening"),
    ("hey, i'm new here", "opening"),
    ("i've never done this before but hi", "opening"),
    ("what kind of music do you like", "opening"),
    ("do you have any hobbies", "opening"),
    ("what's your favorite movie", "opening"),
    ("where do you work", "opening"),
    ("are you a student", "opening"),
    ("what are you studying", "opening"),
    ("where did you grow up", "opening"),
    ("do you have siblings", "opening"),
    ("what's your zodiac sign", "opening"),
    ("you have a great smile", "opening"),
    ("i like your style", "opening"),
    ("do you live alone", "opening"),

    # ── warming_up (32 examples) ──
    ("haha yeah i love that movie too!", "warming_up"),
    ("omg same! that's so cool", "warming_up"),
    ("no way, me too!", "warming_up"),
    ("that's really interesting, tell me more", "warming_up"),
    ("you're easy to talk to", "warming_up"),
    ("i enjoy talking to you", "warming_up"),
    ("haha you're funny", "warming_up"),
    ("we have so much in common", "warming_up"),
    ("i feel like i've known you forever", "warming_up"),
    ("you're different from other people", "warming_up"),
    ("this is fun", "warming_up"),
    ("i can't believe we like the same things", "warming_up"),
    ("you get me", "warming_up"),
    ("i love your sense of humor", "warming_up"),
    ("we should hang out sometime", "warming_up"),
    ("мне нравится с тобой разговаривать", "warming_up"),
    ("ты интересный человек", "warming_up"),
    ("мы так похожи", "warming_up"),
    ("glad we started talking", "warming_up"),
    ("you have good taste", "warming_up"),
    ("ok now i'm curious about you", "warming_up"),
    ("you're making me smile", "warming_up"),
    ("keep going i'm interested", "warming_up"),
    ("wait that's actually so cool", "warming_up"),
    ("i wanna know more about you", "warming_up"),
    ("you're not like most people", "warming_up"),
    ("i look forward to your texts", "warming_up"),
    ("talking to you makes my day better", "warming_up"),
    ("you always know what to say", "warming_up"),
    ("i'm starting to really like you", "warming_up"),
    ("we vibe so well", "warming_up"),
    ("do you believe in fate? because this feels right", "warming_up"),

    # ── flowing (32 examples) ──
    ("omg you won't believe what happened today", "flowing"),
    ("so anyway, like i was saying", "flowing"),
    ("hahaha that reminds me of this time", "flowing"),
    ("ok but listen to this", "flowing"),
    ("wait wait wait i need to tell you something", "flowing"),
    ("oh that's so funny because", "flowing"),
    ("speaking of that, did you know", "flowing"),
    ("yo check this out", "flowing"),
    ("ok so update on that thing i told you about", "flowing"),
    ("lol yeah and then what happened next was crazy", "flowing"),
    ("also forgot to tell you", "flowing"),
    ("by the way", "flowing"),
    ("oh and another thing", "flowing"),
    ("so remember that thing i mentioned", "flowing"),
    ("haha yeah exactly! and also", "flowing"),
    ("представляешь что случилось", "flowing"),
    ("а кстати, я забыл рассказать", "flowing"),
    ("ну и что было дальше", "flowing"),
    ("you know what else is funny", "flowing"),
    ("this is random but", "flowing"),
    ("ok i have a story for you", "flowing"),
    ("let me tell you about my day", "flowing"),
    ("the craziest thing just happened", "flowing"),
    ("oh wait i just remembered", "flowing"),
    ("you'll love this", "flowing"),
    ("so get this", "flowing"),
    ("dying to tell you about today", "flowing"),
    ("girl/dude you won't believe this", "flowing"),
    ("update: it gets worse lol", "flowing"),
    ("ok plot twist", "flowing"),
    ("this is the best part", "flowing"),
    ("i can't stop thinking about what you said earlier", "flowing"),

    # ── deep (35 examples) ──
    ("i've never told anyone this before", "deep"),
    ("you know, sometimes i wonder about the meaning of life", "deep"),
    ("i want to be completely honest with you about my past", "deep"),
    ("do you ever feel like you don't belong anywhere", "deep"),
    ("my biggest fear is being alone forever", "deep"),
    ("i think about my childhood a lot", "deep"),
    ("my parents' divorce really affected me", "deep"),
    ("i struggle with anxiety and it's hard to talk about", "deep"),
    ("i've never been this vulnerable with anyone", "deep"),
    ("what do you think happens after we die", "deep"),
    ("do you believe in destiny", "deep"),
    ("i have trust issues because of my ex", "deep"),
    ("sometimes i feel like i'm not good enough", "deep"),
    ("i want you to know the real me", "deep"),
    ("my dream is to actually make a difference in the world", "deep"),
    ("i used to be really depressed and it changed me", "deep"),
    ("family means everything to me because", "deep"),
    ("the moment i realized i needed to change was", "deep"),
    ("я никому этого не рассказывала", "deep"),
    ("иногда я чувствую себя потерянной", "deep"),
    ("у меня есть страхи о которых я не говорю", "deep"),
    ("what scares you the most about the future", "deep"),
    ("do you think people can really change", "deep"),
    ("i've been hurt so many times", "deep"),
    ("you're the first person i can be myself with", "deep"),
    ("i want to build something real with you", "deep"),
    ("do you ever feel disconnected from everything", "deep"),
    ("my insecurities hold me back sometimes", "deep"),
    ("i think love is the most important thing in life", "deep"),
    ("losing my grandma changed everything for me", "deep"),
    ("sometimes i cry and i don't even know why", "deep"),
    ("i want us to always be this honest with each other", "deep"),
    ("there's something about you that makes me feel safe", "deep"),
    ("i've been thinking about where this is going", "deep"),
    ("what's your deepest regret", "deep"),

    # ── conflict (35 examples) ──
    ("you know what, forget it", "conflict"),
    ("i'm so tired of this same argument", "conflict"),
    ("you clearly don't care about my feelings", "conflict"),
    ("this is exactly what i'm talking about", "conflict"),
    ("you always make it about yourself", "conflict"),
    ("i can't keep doing this", "conflict"),
    ("you never take my side", "conflict"),
    ("that really hurt me", "conflict"),
    ("i feel like you don't listen", "conflict"),
    ("we keep going in circles", "conflict"),
    ("i'm upset and you're making it worse", "conflict"),
    ("you don't understand how i feel", "conflict"),
    ("why do you always do this to me", "conflict"),
    ("i feel disrespected", "conflict"),
    ("you broke my trust", "conflict"),
    ("i told you this would happen", "conflict"),
    ("you make me feel invisible", "conflict"),
    ("i need you to actually hear me", "conflict"),
    ("опять ты начинаешь", "conflict"),
    ("ты меня не слышишь", "conflict"),
    ("мне надоело", "conflict"),
    ("ты всегда делаешь по-своему", "conflict"),
    ("i'm not gonna pretend everything's fine", "conflict"),
    ("the way you talked to me was not okay", "conflict"),
    ("do you even realize what you did", "conflict"),
    ("i feel like you take me for granted", "conflict"),
    ("you're dismissing my feelings again", "conflict"),
    ("this isn't working", "conflict"),
    ("i'm really hurt right now", "conflict"),
    ("you said you'd change but you didn't", "conflict"),
    ("actions speak louder than words", "conflict"),
    ("i feel like we're growing apart", "conflict"),
    ("you chose them over me", "conflict"),
    ("i'm questioning everything right now", "conflict"),
    ("ты мне обещал но не сделал", "conflict"),

    # ── cooling_down (30 examples) ──
    ("ok", "cooling_down"),
    ("fine", "cooling_down"),
    ("k", "cooling_down"),
    ("whatever", "cooling_down"),
    ("sure", "cooling_down"),
    ("mhm", "cooling_down"),
    ("yeah", "cooling_down"),
    ("cool", "cooling_down"),
    ("right", "cooling_down"),
    ("nice", "cooling_down"),
    ("lol ok", "cooling_down"),
    ("haha yeah", "cooling_down"),
    ("ig", "cooling_down"),
    ("idk", "cooling_down"),
    ("nothing", "cooling_down"),
    ("ладно", "cooling_down"),
    ("ок", "cooling_down"),
    ("ну да", "cooling_down"),
    ("норм", "cooling_down"),
    ("угу", "cooling_down"),
    ("it's fine", "cooling_down"),
    ("don't worry about it", "cooling_down"),
    ("nvm", "cooling_down"),
    ("not really", "cooling_down"),
    ("i guess", "cooling_down"),
    ("if you say so", "cooling_down"),
    ("up to you", "cooling_down"),
    ("doesn't matter", "cooling_down"),
    ("i don't care", "cooling_down"),
    ("забей", "cooling_down"),

    # ── makeup (30 examples) ──
    ("i'm sorry, i was wrong", "makeup"),
    ("can we please talk about this", "makeup"),
    ("i hate fighting with you", "makeup"),
    ("i miss how we were", "makeup"),
    ("you're right, i messed up", "makeup"),
    ("i don't want to lose you", "makeup"),
    ("let's not fight anymore", "makeup"),
    ("i love you, even when we argue", "makeup"),
    ("can we start over", "makeup"),
    ("i'm sorry for what i said", "makeup"),
    ("i was being an idiot", "makeup"),
    ("please forgive me", "makeup"),
    ("i'll do better, i promise", "makeup"),
    ("you mean too much to me to fight like this", "makeup"),
    ("i was being selfish and i'm sorry", "makeup"),
    ("прости меня", "makeup"),
    ("я не хочу ссориться", "makeup"),
    ("давай помиримся", "makeup"),
    ("я была неправа", "makeup"),
    ("ты важнее любой ссоры", "makeup"),
    ("i heard what you said and you're right", "makeup"),
    ("i'll never say that again", "makeup"),
    ("can i make it up to you", "makeup"),
    ("i'm not perfect but i'm trying", "makeup"),
    ("i want to fix this", "makeup"),
    ("i care about you too much to let this ruin us", "makeup"),
    ("the fight was stupid, i'm sorry", "makeup"),
    ("you deserve an apology and you have it", "makeup"),
    ("i should have listened instead of reacting", "makeup"),
    ("я обещаю измениться", "makeup"),
]

# ═══════════════════════════════════════════════════════════════════
#  3. EMOTIONAL TONE CLASSIFICATION
# ═══════════════════════════════════════════════════════════════════
# Based on Plutchik's Wheel of Emotions + Relationship-Specific Tones

EMOTIONAL_TONE_DATA: List[Tuple[str, str]] = [
    # ── joy (35 examples) ──
    ("this is amazing!!!", "joy"),
    ("i'm so happy right now", "joy"),
    ("best day ever", "joy"),
    ("omg yessss!!!", "joy"),
    ("i can't stop smiling", "joy"),
    ("this made my day", "joy"),
    ("i'm literally so excited", "joy"),
    ("YESSS", "joy"),
    ("i'm on top of the world", "joy"),
    ("everything is perfect", "joy"),
    ("today was incredible", "joy"),
    ("i feel so alive", "joy"),
    ("you just made me the happiest person", "joy"),
    ("i'm beaming", "joy"),
    ("life is beautiful", "joy"),
    ("я так счастлива", "joy"),
    ("это лучший день", "joy"),
    ("я в восторге", "joy"),
    ("let's celebrate!", "joy"),
    ("omg i'm so proud!!", "joy"),
    ("i literally screamed", "joy"),
    ("this is the best news", "joy"),
    ("i'm over the moon", "joy"),
    ("i feel so blessed", "joy"),
    ("nothing can ruin my mood today", "joy"),
    ("today was so much fun", "joy"),
    ("i laughed so hard", "joy"),
    ("this is everything", "joy"),
    ("i feel giddy", "joy"),
    ("living my best life rn", "joy"),
    ("i can't believe this is real", "joy"),
    ("pure happiness", "joy"),
    ("my heart is so full", "joy"),
    ("couldn't be happier", "joy"),
    ("всё отлично!", "joy"),

    # ── love (35 examples) ──
    ("i love you with all my heart", "love"),
    ("you're the most wonderful person i know", "love"),
    ("being with you feels like magic", "love"),
    ("i adore everything about you", "love"),
    ("my love for you grows every day", "love"),
    ("you're my whole world", "love"),
    ("i never want to let you go", "love"),
    ("you have my heart completely", "love"),
    ("i'm so in love with you", "love"),
    ("loving you is the easiest thing", "love"),
    ("you make my soul happy", "love"),
    ("there's nobody like you", "love"),
    ("you're my everything", "love"),
    ("i'm crazy about you", "love"),
    ("you light up my life", "love"),
    ("я тебя обожаю", "love"),
    ("моя любимая", "love"),
    ("ты моя жизнь", "love"),
    ("люблю тебя безумно", "love"),
    ("ты моё всё", "love"),
    ("holding you is my favorite feeling", "love"),
    ("i see my future in your eyes", "love"),
    ("you're the reason i believe in love", "love"),
    ("my heart skips a beat when i see your name", "love"),
    ("you're my safe place", "love"),
    ("i love the way you love me", "love"),
    ("forever sounds perfect with you", "love"),
    ("you're the best part of my day", "love"),
    ("i found home in you", "love"),
    ("every love song makes me think of you", "love"),
    ("you own my heart", "love"),
    ("i'm yours, completely", "love"),
    ("i fall for you more every day", "love"),
    ("you're my dream come true", "love"),
    ("ты лучшее что у меня есть", "love"),

    # ── anger (35 examples) ──
    ("i'm furious right now", "anger"),
    ("this makes me so angry", "anger"),
    ("are you kidding me", "anger"),
    ("i can't believe this", "anger"),
    ("that's absolutely unacceptable", "anger"),
    ("i'm livid", "anger"),
    ("this is the last straw", "anger"),
    ("how dare you", "anger"),
    ("you infuriate me", "anger"),
    ("i'm boiling with rage", "anger"),
    ("that's it, i'm done", "anger"),
    ("stop pushing my buttons", "anger"),
    ("you're really testing my patience", "anger"),
    ("i want to scream", "anger"),
    ("that was SO wrong", "anger"),
    ("я в ярости", "anger"),
    ("это возмутительно", "anger"),
    ("я вне себя от злости", "anger"),
    ("как ты посмел", "anger"),
    ("this is infuriating", "anger"),
    ("you made me so mad", "anger"),
    ("i've had it", "anger"),
    ("i'm seeing red", "anger"),
    ("that's the most inconsiderate thing", "anger"),
    ("you know exactly what you did", "anger"),
    ("i'm so fed up", "anger"),
    ("don't you DARE", "anger"),
    ("this is outrageous", "anger"),
    ("i can't even look at you right now", "anger"),
    ("you always ruin everything", "anger"),
    ("i'm not gonna take this anymore", "anger"),
    ("это невыносимо", "anger"),
    ("me бесит это всё", "anger"),
    ("это последняя капля", "anger"),
    ("я терпеть не могу", "anger"),

    # ── sadness (35 examples) ──
    ("i feel so empty", "sadness"),
    ("my heart is heavy", "sadness"),
    ("i can't stop the tears", "sadness"),
    ("everything hurts", "sadness"),
    ("i feel so hopeless", "sadness"),
    ("i just want to curl up and disappear", "sadness"),
    ("the pain won't go away", "sadness"),
    ("i'm so heartbroken", "sadness"),
    ("nothing feels right anymore", "sadness"),
    ("i'm drowning in sadness", "sadness"),
    ("why does it have to hurt so much", "sadness"),
    ("i feel worthless", "sadness"),
    ("nobody understands", "sadness"),
    ("i lost something i can never get back", "sadness"),
    ("the world feels grey", "sadness"),
    ("мне так больно", "sadness"),
    ("я чувствую пустоту", "sadness"),
    ("всё рушится", "sadness"),
    ("не могу перестать плакать", "sadness"),
    ("мне так одиноко", "sadness"),
    ("i'm grieving", "sadness"),
    ("this emptiness won't leave", "sadness"),
    ("i feel gutted", "sadness"),
    ("my chest physically aches", "sadness"),
    ("i don't know how to be happy anymore", "sadness"),
    ("some wounds don't heal", "sadness"),
    ("i feel like crying but nothing comes out", "sadness"),
    ("the silence is deafening", "sadness"),
    ("i'm tired of pretending i'm fine", "sadness"),
    ("everything reminds me of what i lost", "sadness"),
    ("i feel so fragile", "sadness"),
    ("life isn't fair", "sadness"),
    ("i've been in bed all day", "sadness"),
    ("i miss the way things used to be", "sadness"),
    ("на душе тяжело", "sadness"),

    # ── surprise (30 examples) ──
    ("wait WHAT", "surprise"),
    ("no way!!!", "surprise"),
    ("are you serious right now", "surprise"),
    ("i did NOT expect that", "surprise"),
    ("omg you scared me", "surprise"),
    ("you're kidding", "surprise"),
    ("shut up, really?!", "surprise"),
    ("i'm shocked", "surprise"),
    ("that came out of nowhere", "surprise"),
    ("plot twist!", "surprise"),
    ("what just happened", "surprise"),
    ("i'm speechless", "surprise"),
    ("did that actually happen", "surprise"),
    ("my jaw just dropped", "surprise"),
    ("i can't process this", "surprise"),
    ("не может быть", "surprise"),
    ("ты шутишь?!", "surprise"),
    ("я в шоке", "surprise"),
    ("this blew my mind", "surprise"),
    ("i never saw that coming", "surprise"),
    ("hold up what", "surprise"),
    ("you just blew my mind", "surprise"),
    ("this changes everything", "surprise"),
    ("excuse me??", "surprise"),
    ("i'm literally shook", "surprise"),
    ("wait back up", "surprise"),
    ("come again??", "surprise"),
    ("nah you're lying", "surprise"),
    ("absolutely gobsmacked", "surprise"),
    ("say that again slowly", "surprise"),

    # ── fear (30 examples) ──
    ("i'm really scared", "fear"),
    ("what if something goes wrong", "fear"),
    ("i can't stop worrying", "fear"),
    ("i'm terrified", "fear"),
    ("this is freaking me out", "fear"),
    ("i have a bad feeling about this", "fear"),
    ("i'm so anxious right now", "fear"),
    ("what if they find out", "fear"),
    ("i'm dreading tomorrow", "fear"),
    ("my anxiety is through the roof", "fear"),
    ("i feel unsafe", "fear"),
    ("this keeps me up at night", "fear"),
    ("i'm paranoid", "fear"),
    ("something feels off", "fear"),
    ("i don't know what's gonna happen", "fear"),
    ("мне страшно", "fear"),
    ("я очень переживаю", "fear"),
    ("у меня паника", "fear"),
    ("i'm having a panic attack", "fear"),
    ("my heart is racing", "fear"),
    ("i feel like something bad is coming", "fear"),
    ("i can't breathe", "fear"),
    ("i'm walking on eggshells", "fear"),
    ("this uncertainty is killing me", "fear"),
    ("i'm afraid of losing you", "fear"),
    ("i keep thinking worst case scenarios", "fear"),
    ("i'm really nervous", "fear"),
    ("everything feels dangerous", "fear"),
    ("я боюсь что всё кончится", "fear"),
    ("i'm spiraling", "fear"),

    # ── desire (35 examples) ──
    ("i want you so bad", "desire"),
    ("i need you right now", "desire"),
    ("you're making me feel things", "desire"),
    ("i can't get you out of my head", "desire"),
    ("i crave your touch", "desire"),
    ("you drive me wild", "desire"),
    ("come closer", "desire"),
    ("i want all of you", "desire"),
    ("you're intoxicating", "desire"),
    ("the chemistry between us is insane", "desire"),
    ("i'm so attracted to you", "desire"),
    ("you make my heart race", "desire"),
    ("there's a tension between us", "desire"),
    ("i've never wanted someone this much", "desire"),
    ("the way you look at me", "desire"),
    ("хочу тебя", "desire"),
    ("ты сводишь меня с ума", "desire"),
    ("я не могу без тебя", "desire"),
    ("i keep replaying our moments in my head", "desire"),
    ("just your voice does things to me", "desire"),
    ("i'm counting the minutes until i see you", "desire"),
    ("you have no idea what you do to me", "desire"),
    ("i'm drawn to you", "desire"),
    ("being near you is electric", "desire"),
    ("the anticipation is killing me", "desire"),
    ("i want to be with you tonight", "desire"),
    ("you're so magnetic", "desire"),
    ("every part of me wants every part of you", "desire"),
    ("this longing is unbearable", "desire"),
    ("i need your warmth", "desire"),
    ("you awaken something in me", "desire"),
    ("my whole body reacts to you", "desire"),
    ("i'm burning for you", "desire"),
    ("the tension is palpable", "desire"),
    ("я схожу по тебе с ума", "desire"),

    # ── tenderness (35 examples) ──
    ("let me take care of you", "tenderness"),
    ("you're precious to me", "tenderness"),
    ("i just want to hold you", "tenderness"),
    ("you're so adorable", "tenderness"),
    ("watching you sleep is my favorite thing", "tenderness"),
    ("i want to protect you", "tenderness"),
    ("your happiness means everything to me", "tenderness"),
    ("come here, let me hug you", "tenderness"),
    ("you look so peaceful", "tenderness"),
    ("i'll take care of everything", "tenderness"),
    ("you're my soft spot", "tenderness"),
    ("i just want you to be happy", "tenderness"),
    ("you deserve all the good things", "tenderness"),
    ("let me make you feel better", "tenderness"),
    ("i wish i could take your pain away", "tenderness"),
    ("ты моя малышка", "tenderness"),
    ("хочу о тебе заботиться", "tenderness"),
    ("ты самая нежная", "tenderness"),
    ("иди ко мне, обниму", "tenderness"),
    ("я хочу чтобы тебе было хорошо", "tenderness"),
    ("you're the sweetest soul", "tenderness"),
    ("my heart melts for you", "tenderness"),
    ("you make me so soft", "tenderness"),
    ("i want to wrap you in a blanket", "tenderness"),
    ("i'll always be gentle with your heart", "tenderness"),
    ("you bring out my softer side", "tenderness"),
    ("i never knew i could care this much", "tenderness"),
    ("seeing you happy makes me happy", "tenderness"),
    ("i want to be your safe space", "tenderness"),
    ("you're so delicate and beautiful", "tenderness"),
    ("i handle your heart with care", "tenderness"),
    ("you're my baby", "tenderness"),
    ("i love how gentle you are", "tenderness"),
    ("let me be your comfort", "tenderness"),
    ("я нежно тебя люблю", "tenderness"),

    # ── neutral (30 examples) ──
    ("okay", "neutral"),
    ("i see", "neutral"),
    ("makes sense", "neutral"),
    ("got it", "neutral"),
    ("understood", "neutral"),
    ("noted", "neutral"),
    ("alright", "neutral"),
    ("interesting", "neutral"),
    ("that's good to know", "neutral"),
    ("fair enough", "neutral"),
    ("right", "neutral"),
    ("sure thing", "neutral"),
    ("oh okay", "neutral"),
    ("i'll think about it", "neutral"),
    ("let me check", "neutral"),
    ("понятно", "neutral"),
    ("хорошо", "neutral"),
    ("ясно", "neutral"),
    ("окей", "neutral"),
    ("sounds about right", "neutral"),
    ("that works", "neutral"),
    ("yep", "neutral"),
    ("i guess so", "neutral"),
    ("why not", "neutral"),
    ("maybe", "neutral"),
    ("i'll let you know", "neutral"),
    ("hmm", "neutral"),
    ("we'll see", "neutral"),
    ("it is what it is", "neutral"),
    ("можно", "neutral"),

    # ── playful (35 examples) ──
    ("you're so dumb i love it 😂", "playful"),
    ("oh you think you're clever huh", "playful"),
    ("bet you can't guess", "playful"),
    ("no you hang up first", "playful"),
    ("lmaooo you're the worst", "playful"),
    ("wanna play a game", "playful"),
    ("i'm totally beating you next time", "playful"),
    ("you're such a show-off 😂", "playful"),
    ("nerd alert", "playful"),
    ("ok mr cool guy", "playful"),
    ("pffft as if", "playful"),
    ("oh please 🙄😂", "playful"),
    ("you wish!", "playful"),
    ("keep dreaming", "playful"),
    ("your ego is showing", "playful"),
    ("ты такой смешной", "playful"),
    ("дурачок 😂", "playful"),
    ("спорим что нет", "playful"),
    ("try harder", "playful"),
    ("is that your best", "playful"),
    ("catch me if you can", "playful"),
    ("you wouldn't survive a day without me", "playful"),
    ("i'm too cool for you", "playful"),
    ("ok boomer", "playful"),
    ("you're cancelled 😂", "playful"),
    ("i'm screaming 😭😂", "playful"),
    ("the shade", "playful"),
    ("you just got roasted", "playful"),
    ("i see what you did there", "playful"),
    ("smooth operator", "playful"),
    ("ok flex", "playful"),
    ("main character energy", "playful"),
    ("villain arc activated", "playful"),
    ("bestie behavior", "playful"),
    ("ну ты и выдумщик", "playful"),
]


def _merge_and_dedupe(
    base: List[Tuple[str, str]], extra: List[Tuple[str, str]]
) -> List[Tuple[str, str]]:
    """Merge two datasets, removing exact duplicates while preserving order."""
    seen = set()
    merged = []
    for item in base + extra:
        if item not in seen:
            seen.add(item)
            merged.append(item)
    return merged


def get_romantic_intent_data() -> List[Tuple[str, str]]:
    """Get romantic intent training data (original + generated + real conversations)."""
    result = ROMANTIC_INTENT_DATA
    try:
        from training.generate_expanded_data import generate_all_data
        ri, _, _ = generate_all_data()
        result = _merge_and_dedupe(result, ri)
    except ImportError:
        pass
    try:
        from training.real_conversations_data import get_real_romantic_intent
        result = _merge_and_dedupe(result, get_real_romantic_intent())
    except ImportError:
        pass
    return result


def get_conversation_stage_data() -> List[Tuple[str, str]]:
    """Get conversation stage training data (original + generated + real conversations)."""
    result = CONVERSATION_STAGE_DATA
    try:
        from training.generate_expanded_data import generate_all_data
        _, cs, _ = generate_all_data()
        result = _merge_and_dedupe(result, cs)
    except ImportError:
        pass
    try:
        from training.real_conversations_data import get_real_conversation_stage
        result = _merge_and_dedupe(result, get_real_conversation_stage())
    except ImportError:
        pass
    return result


def get_emotional_tone_data() -> List[Tuple[str, str]]:
    """Get emotional tone training data (original + generated + real conversations)."""
    result = EMOTIONAL_TONE_DATA
    try:
        from training.generate_expanded_data import generate_all_data
        _, _, et = generate_all_data()
        result = _merge_and_dedupe(result, et)
    except ImportError:
        pass
    try:
        from training.real_conversations_data import get_real_emotional_tone
        result = _merge_and_dedupe(result, get_real_emotional_tone())
    except ImportError:
        pass
    return result


def get_all_data() -> Dict[str, List[Tuple[str, str]]]:
    """Get all training datasets (original + generated)."""
    return {
        "romantic_intent": get_romantic_intent_data(),
        "conversation_stage": get_conversation_stage_data(),
        "emotional_tone": get_emotional_tone_data(),
    }


def get_data_stats() -> Dict[str, Any]:
    """Get statistics about the training data."""
    all_data = get_all_data()
    stats = {}

    for name, data in all_data.items():
        labels = [label for _, label in data]
        unique_labels = set(labels)
        label_counts = {l: labels.count(l) for l in sorted(unique_labels)}
        stats[name] = {
            "total_examples": len(data),
            "num_classes": len(unique_labels),
            "classes": sorted(unique_labels),
            "class_distribution": label_counts,
            "min_per_class": min(label_counts.values()),
            "max_per_class": max(label_counts.values()),
        }

    stats["total_examples_all"] = sum(len(d) for d in all_data.values())
    return stats


if __name__ == "__main__":
    import json

    stats = get_data_stats()
    print(json.dumps(stats, indent=2))
    print(f"\nTotal training examples: {stats['total_examples_all']}")
